### ISSUE TITLE
Troubles installing

### ISSUE THREAD

**Issue by roelvan** [fede-rodes/facebook-accounts-patched#1]
Thanks for this patch! I followed your steps but I am having some dependencies troubles:
```
While selecting package versions:
   error: No version of facebook satisfies all constraints: @=1.2.2, @=1.2.8
   Constraints on package "facebook":
   * facebook@=1.2.2 <- top level
   * facebook@=1.2.8 <- top level
   * facebook@1.2.7 <- accounts-facebook 1.0.10
```

**Comment by fede-rodes** [comment]
Hi @roelvan 

Try modifying the package.js file in the facebook folder by switching from version "1.2.2" to version "1.2.7". I had a similar issue with my version of accounts-facebook. 

It should look like this

Package.describe({
  summary: "Facebook OAuth flow",
  version: "1.2.7"
});

Let me know if it solves the issue :)

**Comment by fede-rodes** [comment]
@roelvan 

Other approach would be to leave the facebook package in its current version (1.2.2) but to downgrade your version of facebook-accounts to 'accounts-facebook@1.0.6'.

You can achieve this by simply going to your .meteor/versions file (inside your app) and manually update the facebook-account package version from 1.0.10 to 1.0.6. Then, re-run your app.

**Comment by crsssl** [comment]
@fede-rodes Thanks for this. You're a life saver.

Yes, just installing the patch in your `packages` directory, while retaining `accounts-facebook@1.0.6`, works well.

**Comment by kenjoe** [comment]
I try to downgrade my accounts-facebook@1.0.8 to 1.0.6 by manually editing the version on .meteor/versions file, but then after my app rerun the accounts-facebook package always re-update to 1.0.8. Is there any way I can downgrade my accounts-facebook package from 1.0.8 to 1.0.6? I'm in Meteor verion 1.3.1

**Comment by fede-rodes** [comment]
Hey @kenjoe 

In my case, if I upgrade my meteor project to 1.3.1, then I need to modify the package.js file in the facebook folder by switching from version "1.2.2" to version "1.2.5". 

It should look like this

Package.describe({
summary: "Facebook OAuth flow",
version: "1.2.5"
});

Let me know if it works

**Comment by kenjoe** [comment]
Yes! It works! Thank you! :)

**Comment by roelvan** [comment]
@fede-rodes Thanks for the extra explanation. It works too here! Today, I also upgraded Meteor to 1.4 to be more future proof.

**Comment by juliomac** [comment]
Thanks! Same happened to me.

I am on Meteor Version 1.3.4.1 and what worked was changing to version 1.2.8
